emcamp/emcamp/urls.py
from django.contrib import admin
from django.urls import path

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]
from django.conf.urls import include, url

from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    # url(r'^users/', include('users.urls')),
    url(r'^', include("reddit.urls")),
    url(r'^', include("users.urls")),
    url('posts/', include('posts.urls', namespace="posts")),
    url('groups/',include('groups.urls', namespace="groups")),
]

emcamp/groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

emcamp/posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/in/(?P<pk>\d+)/$", views.CreatePost.as_view(), name="create1"),
    url(r"comment/in/(?P<pk>\d+)/$", views.CreateComment.as_view(), name="create2"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"comment/delete/(?P<pk>\d+)/$",views.DeleteComment.as_view(),name="delete_comment"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]


emcamp/groups/models.py


# Create your models here.
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.text import slugify
# from accounts.models import User

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()



class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships",on_delete=models.CASCADE,)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE,)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

emcamp/groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from groups.models import Group,GroupMember
from . import models


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

emcamp/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}


{% endblock %}

emcamp/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block content %}

<h1>{{group.name}}</h1>
<h2> Member Count: {{group.members.count}}</h2>

  <div class="content">


				{% if user in group.members.all %}
					<a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
                    <a href="{% url 'posts:create1' pk=group.pk %}" class="btn btn-lg btn-fill btn-warning" ><span class="glyphicon glyphicon-ok-circle"></span> Ask Question / Post </a></li>
                    {% else %}
					<a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
				{% endif %}



</div>

<div class="col-md-8 list-group">
	{% if group.posts.count == 0 %}
	<h2>No posts in this group yet!</h2>

	{% else %}
        {% for post in group.posts.all %}
   
        <div class="post media list-group-item" style="margin-top: 9px;">
            <h3 class="title list-group-item-heading" style="color: black !important; margin-bottom: 10px;"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.question }}</a></h3>
            <div class="media-body">
                <h5 class="media-heading">
                    <span class="username" style="color: black;">By:<a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
                    <time class="time" style="color: black;">{{ post.created_at }}</time>
                </h5>
                <span style="color:black;"><span class="badge">{{ post.comments.count }}</span> comment{{ post.comments.count|pluralize}}</span>
                <div class="media-footer">
                    {% if user.is_authenticated and post.user == user and not hide_delete %}
                    <a href="{% url 'posts:delete' pk=post.pk %}" class="btn btn-danger btn-large" style="color: white;margin-top: 4px;"> Delete</a>
                    {% endif %}
                </div>
            </div>
        </div>
    
		{% endfor %}
	{% endif %}
</div>
{% endblock %}

emcamp/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{{form|crispy }}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

emcamp/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block content %}
<div style="margin-top: 5px;">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Spaces</h2>

			<h4 style="margin-bottom: 20px;">Join a Space with a shared interest and be the part of the community!</h4>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Space!</a>
	{% endif %}

</div>

{% if object_list %}
<div class="col-md-6 intro" style="margin-top: 6px;">
	<h3>Spaces you follow!</h3>
	<div class="list-group">
		{% for group in object_list %}
		{% if user in group.members.all %}
		  <a class="list-group-item" style="margin-bottom: 5px;" href="{% url 'groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endif %}
		{% endfor %}
	</div>
</div>

<div class="col-md-6 intro" style="margin-top: 6px;">
	<h3>Spaces you might be interested in!</h3>
	<div class="list-group">
		{% for group in object_list %}
		{% if user not in group.members.all %}
		  <a class="list-group-item" style="margin-bottom: 5px;" href="{% url 'groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endif %}
		{% endfor %}
	</div>
</div>
{% else %}
<div class="col-md-12 intro" style="margin-top: 10px;font-size: xx-large;">
	No space yet! Create one to get started!
</div>

{% endif %}
{% endblock %}