emcamp/emcamp/urls.py
from django.contrib import admin
from django.urls import path

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]
from django.conf.urls import include, url

from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    # url(r'^users/', include('users.urls')),
    url(r'^', include("reddit.urls")),
    url(r'^', include("users.urls")),
    url('posts/', include('posts.urls', namespace="posts")),
    url('groups/',include('groups.urls', namespace="groups")),
]

emcamp/posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/in/(?P<pk>\d+)/$", views.CreatePost.as_view(), name="create1"),
    url(r"comment/in/(?P<pk>\d+)/$", views.CreateComment.as_view(), name="create2"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"comment/delete/(?P<pk>\d+)/$",views.DeleteComment.as_view(),name="delete_comment"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]


emcamp/comments/models.py
from django.db import models

# Create your models here.

emcamp/posts/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models

import misaka

from groups.models import  Group

from django.contrib.auth import get_user_model
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    question = models.CharField(max_length=255)
    # question_html = models.TextField(editable=False)
    description=models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False)
    picture=models.ImageField(upload_to='pics',blank=True)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True,on_delete=models.CASCADE,)

    def __str__(self):
        return self.question

    def save(self, *args, **kwargs):
        self.question_html = misaka.html(self.question)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "question"]

class Comment1(models.Model):
    post = models.ForeignKey(Post, related_name='comments',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    comment = models.TextField()
    text_html = models.TextField(editable=False)
    pic=models.ImageField(upload_to='pics',blank=True)
    user = models.ForeignKey(User, related_name="comments",on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.text_html = misaka.html(self.comment)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        # return reverse("posts:single" , kwargs={"slug": self.slug})
        return reverse("posts:single" , kwargs={"username":self.post.user.username,"pk":self.post.pk})

    def __str__(self):
        return self.comment

emcamp/posts/forms.py
from django import forms

from posts import models


class PostForm(forms.ModelForm):
    class Meta:
        # fields = ("message", "group")
        fields = ('question','description','picture')
        model = models.Post




class CommentForm(forms.ModelForm):
    class Meta:
        # fields = ("message", "group")
        fields = ('comment','pic')
        model = models.Comment1

emcamp/comments/views.py
from django.shortcuts import render

# Create your views here.

emcamp/posts/views.py
# from django.shortcuts import render

# # Create your views here.
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from django.shortcuts import get_object_or_404
from groups.models import Group

from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('question','description','picture')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.group=get_object_or_404(Group,pk=self.kwargs.get('pk'))
        if 'picture' in self.request.FILES:
            self.object.picture=self.request.FILES['picture']
        self.object.save()
        return super().form_valid(form)


class CreateComment(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('comment','pic')
    model = models.Comment1

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.post=get_object_or_404(models.Post,pk=self.kwargs.get('pk'))
        if 'pic' in self.request.FILES:
            self.object.pic=self.request.FILES['pic']
        self.object.save()
        return super().form_valid(form)


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )



class DeleteComment(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Comment1
    select_related = ("user", "post")
    success_url = reverse_lazy("index")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Comment Deleted")
        return super().delete(*args, **kwargs)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("index")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

emcamp/posts/templates/posts/comment_confirm_delete.html
{% extends "posts/post_base.html" %}


{% block content %}
<h3>Are you sure you want to delete this comment?</h3>

<div class="posts">
	<div class="post media list-group-item">
		<h3 class="title list-group-item-heading" style="color: black !important; margin-bottom: 10px;font-size: medium;">{{ comment.comment }}</h3>
		<div class="media-body">
			<h5 class="media-heading">
				<span class="username" style="color: black !important; margin-bottom: 10px;"><a href="{% url 'posts:for_user' username=comment.post.user.username %}">@{{ comment.user.username }}</a></span>
				<time class="time" style="color: black !important; margin-bottom: 10px;">{{ comment.created_at }}</time>
			</h5>

		</div>
	</div>
	
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large" style="margin-top: 4px;">
	<a href="{% url 'posts:single' username=comment.post.user.username pk=comment.post.pk %}" class="btn btn-simple btn-large btn-default" style="margin-top: 4px;">Cancel</a>
</form>

{% endblock %}

emcamp/posts/templates/posts/comment_form.html
{% extends "posts/post_base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h4>Create New Post</h4>
<form method="POST" enctype="multipart/form-data" action="" id="commentForm">
	{% csrf_token %}
	{%  form|crispy %}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>
{% endblock %}

emcamp/posts/templates/posts/post_base.html
{% extends "base.html" %}

<div class="posts-page">
	<div class="container">
		<div class="row">
            {% block content %}
            
            {% endblock %}
		</div>
	</div>
</div>


emcamp/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}


{% block content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	<div class="post media post media list-group-item">
		<h3 class="title list-group-item-heading" style="color: black !important; margin-bottom: 10px;"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}"></a>{{ post.question }}</a></h3>
		<h3 class="title list-group-item-heading" style="color: black !important; margin-bottom: 10px;font-size: medium;">{{ post.description_html|safe }}</h3>
		<div class="media-body">
			<h5 class="media-heading">
				<span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
				<time class="time" style="color: black !important; margin-bottom: 10px;">{{ post.created_at }}</time>
				{% if post.group %}
				<span class="group-name" style="color: black !important; margin-bottom: 10px;">in <a href="{% url 'groups:single' slug=post.group.slug %}">{{ post.group.name }}</a></span>
				{% endif %}
			</h5>

		</div>
	</div>
	
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large" style="margin-top: 4px;">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" style="margin-top: 4px;" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

emcamp/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block content %}
<div class="col-md-8">
    <div class="post media ">
        <div class="post media list-group-item" style="margin-top: 9px;"><h3 class="title list-group-item-heading" style="color: black !important; margin-bottom: 10px;font-size: large;">{{ post.question }}</h3></div>
        <div class="post media list-group-item" style="margin-top: 9px; background-color: beige;"><h3 class="title list-group-item-heading" style="color: black !important; margin-bottom: 10px !important; font-size: medium;">{{ post.description_html|safe }}</h3>    
        {% if post.picture %}
        <img src="{{ post.picture.url }}" class="img-responsive" style="width: auto; height:auto;float: left;margin-right: 10px; margin-top: 6px;" /> 
        {%  endif %}
    </div>  
        <div class="media-body">
            <h5 class="media-heading" style="margin-top: 7px;">
                <span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
                <time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
            </h5>
    
    
            <div class="media-footer">
                {% if user.is_authenticated and post.user == user and not hide_delete %}
                <a href="{% url 'posts:delete' pk=post.pk %}" class="btn btn-danger btn-large" style="color: white;"> Delete</a>
                {% endif %}
                {% if user.is_authenticated and user in post.group.members.all %}
                <a class="btn btn-primary btn-comment" href="{% url 'posts:create2' pk=post.pk %}">Add comment</a>
                {% endif %}
    
            </div>
            {% for comment in post.comments.all %}
            <div class="post media list-group-item" style="margin-top: 9px;background-color:rgb(201, 198, 194);" >
                <h3 class="title list-group-item-heading" style="color: black !important; margin-bottom: 10px !important; font-size: medium;">{{ comment.comment }}</h3>
                {% if comment.pic %}
                <img src="{{ comment.pic.url }}" class="img-responsive" style="width: auto; height:auto;float: inherit; margin-right: 10px; margin-top: 6px; margin-bottom: 9px;" /> 
                {% endif %}
                <div class="media-body">
                    <h5 class="media-heading">
                        <span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ comment.user.username }}</a></span>
                        <time class="time" style="color: black;">{{ comment.created_at }}</time>
                    </h5>
            
                    <div class="media-footer">
                        {% if user.is_authenticated and comment.user == user and not hide_delete %}
                            <a href="{% url 'posts:delete_comment' pk=comment.pk %}" title="delete" class="btn btn-simple">
                                <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                                <span class="text-danger icon-label">Delete</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
    
        </div>
    </div>
    
</div>
{% endblock %}

emcamp/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h4>Create New Post</h4>
<form method="POST" enctype="multipart/form-data" action="" id="postForm">
	{% csrf_token %}
	{{ form|crispy }}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>
{% endblock %}

emcamp/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{# {% get_user_groups as user_groups %}#}
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %}#}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>
			



		</div>
	</div>
</div>

<div class="col-md-8">
	{% for post in post_list %}
	<div class="post media">
        <h3>{{ post.message_html|safe }}</h3>
        <div class="media-body">
            <strong>{{ post.user.username }}</strong>
            <h5 class="media-heading">
                <span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
                <time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
                {% if post.group %}
                <span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
                {% endif %}
            </h5>
    
    
    
    
            <div class="media-footer">
                {% if user.is_authenticated and post.user == user and not hide_delete %}
                    <a href="#" title="delete" class="btn btn-simple">
                        <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                        <span class="text-danger icon-label">Delete</span>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
    
	{% endfor %}
</div>
{% endblock %}

emcamp/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block content %}
<div class="col-md-2">
	<h3>@{{ post_user.username }}</h3>
	<p>Your Post History</p>
</div>

<div class="col-md-10" >
	{% for post in post_list %}
	<div class="post media post media list-group-item" style="margin-top: 9px;background-color: bisque;" >
		<h3 class="title list-group-item-heading" style="color: black !important; margin-bottom: 10px;font-size: large;"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.question }}</a></h3>
		<div class="media-body">
			<h5 class="media-heading">
				<span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
				<time class="time" style="color: black;">{{ post.created_at }}</time>
				{% if post.group %}
				<span class="group-name" style="color: black;">in <a href="{% url 'groups:single' slug=post.group.slug %}">{{ post.group.name }}</a></span>
				{% endif %}
			</h5>
	
	
	
	
			<div class="media-footer">
				{% if user.is_authenticated and post.user == user and not hide_delete %}
					<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
						<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
						<span class="text-danger icon-label">Delete</span>
					</a>
				{% endif %}
			</div>
		</div>
	</div>
	
	{% endfor %}
</div>
{% endblock %}