emcamp/emcamp/urls.py
from django.contrib import admin
from django.urls import path

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]
from django.conf.urls import include, url

from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    # url(r'^users/', include('users.urls')),
    url(r'^', include("reddit.urls")),
    url(r'^', include("users.urls")),
    url('posts/', include('posts.urls', namespace="posts")),
    url('groups/',include('groups.urls', namespace="groups")),
]

emcamp/groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

emcamp/posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/in/(?P<pk>\d+)/$", views.CreatePost.as_view(), name="create1"),
    url(r"comment/in/(?P<pk>\d+)/$", views.CreateComment.as_view(), name="create2"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"comment/delete/(?P<pk>\d+)/$",views.DeleteComment.as_view(),name="delete_comment"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]


emcamp/templates/__layout/footer.html
<div id="footer">
    <div class="container">

          <a href="http://elmeriyu.pythonanywhere.com/#">page-officel</a></i>

        </p>
    </div>
</div>

emcamp/templates/__layout/navbar.html
{% load static %}
<nav class="navbar navbar-inverse" style="background:purple">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'frontpage' %}" style="float:left">
                <img src= "{% static 'tn-logo.PNG' %}" height="50" width="50"  />
            </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'frontpage' %}">Home</a></li>
                <li><a href="{% url 'submit' %}">Submit</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right ">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ user }}<img avatar="{{user.username}}" height="85" width="85" class="round"/>
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="/user/{{ user }}">Profile</a></li>
                            <li class="disabled"><a href="#">Messages <span class="badge">0</span></a></li>
                            <li><a href="{% url 'groups:all' %}" class="btn btn-simple" style="margin-top: 7px; font-size:20px;">Spaces</a></li>
                            <li><a href="{% url 'groups:create' %}" class="btn btn-simple" style="margin-top: 7px; font-size:20px;">Create Space</a></li>
                            <li><a href="{% url 'posts:for_user' username=user.username %}" class="btn btn-simple"  style="margin-top: 7px; font-size:20px;">Your Posts</a><li>
                            <li class="divider"></li>
                            <li>
                                <form id="logoutForm" action="/logout/" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="current_page" value="{{ request.path }}">
                                </form>
                                <a onclick="$(this).parent().find('#logoutForm').submit()" href="#">Logout</a>
                            </li>

                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'register' %}">Register</a></li>
                {% endif %}
            </ul>


        </div>
    </div>
</nav>